/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as R500RouteImport } from './routes/500'
import { Route as R404RouteImport } from './routes/404'
import { Route as R403RouteImport } from './routes/403'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedMyNoticesRouteImport } from './routes/_authenticated/my-notices'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSettingsUsersRouteImport } from './routes/_authenticated/settings/users'
import { Route as AuthenticatedSettingsRolesRouteImport } from './routes/_authenticated/settings/roles'
import { Route as AuthenticatedSettingsPermissionsRouteImport } from './routes/_authenticated/settings/permissions'
import { Route as AuthenticatedSettingsMenusRouteImport } from './routes/_authenticated/settings/menus'
import { Route as AuthenticatedSettingsLogsRouteImport } from './routes/_authenticated/settings/logs'
import { Route as AuthenticatedSettingsDictsRouteImport } from './routes/_authenticated/settings/dicts'
import { Route as AuthenticatedOrgPostsRouteImport } from './routes/_authenticated/org/posts'
import { Route as AuthenticatedOrgNoticesRouteImport } from './routes/_authenticated/org/notices'
import { Route as AuthenticatedOrgDirectoryRouteImport } from './routes/_authenticated/org/directory'
import { Route as AuthenticatedOrgDeptsRouteImport } from './routes/_authenticated/org/depts'
import { Route as AuthenticatedOrgChartRouteImport } from './routes/_authenticated/org/chart'
import { Route as AuthenticatedOrgNoticesNoticeIdRouteImport } from './routes/_authenticated/org/notices_.$noticeId'

const R500Route = R500RouteImport.update({
  id: '/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyNoticesRoute = AuthenticatedMyNoticesRouteImport.update({
  id: '/my-notices',
  path: '/my-notices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsUsersRoute =
  AuthenticatedSettingsUsersRouteImport.update({
    id: '/settings/users',
    path: '/settings/users',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRolesRoute =
  AuthenticatedSettingsRolesRouteImport.update({
    id: '/settings/roles',
    path: '/settings/roles',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsPermissionsRoute =
  AuthenticatedSettingsPermissionsRouteImport.update({
    id: '/settings/permissions',
    path: '/settings/permissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsMenusRoute =
  AuthenticatedSettingsMenusRouteImport.update({
    id: '/settings/menus',
    path: '/settings/menus',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsLogsRoute =
  AuthenticatedSettingsLogsRouteImport.update({
    id: '/settings/logs',
    path: '/settings/logs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsDictsRoute =
  AuthenticatedSettingsDictsRouteImport.update({
    id: '/settings/dicts',
    path: '/settings/dicts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrgPostsRoute = AuthenticatedOrgPostsRouteImport.update({
  id: '/org/posts',
  path: '/org/posts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrgNoticesRoute = AuthenticatedOrgNoticesRouteImport.update({
  id: '/org/notices',
  path: '/org/notices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrgDirectoryRoute =
  AuthenticatedOrgDirectoryRouteImport.update({
    id: '/org/directory',
    path: '/org/directory',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrgDeptsRoute = AuthenticatedOrgDeptsRouteImport.update({
  id: '/org/depts',
  path: '/org/depts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrgChartRoute = AuthenticatedOrgChartRouteImport.update({
  id: '/org/chart',
  path: '/org/chart',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrgNoticesNoticeIdRoute =
  AuthenticatedOrgNoticesNoticeIdRouteImport.update({
    id: '/org/notices_/$noticeId',
    path: '/org/notices/$noticeId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/500': typeof R500Route
  '/sign-in': typeof authSignInRoute
  '/account': typeof AuthenticatedAccountRoute
  '/my-notices': typeof AuthenticatedMyNoticesRoute
  '/org/chart': typeof AuthenticatedOrgChartRoute
  '/org/depts': typeof AuthenticatedOrgDeptsRoute
  '/org/directory': typeof AuthenticatedOrgDirectoryRoute
  '/org/notices': typeof AuthenticatedOrgNoticesRoute
  '/org/posts': typeof AuthenticatedOrgPostsRoute
  '/settings/dicts': typeof AuthenticatedSettingsDictsRoute
  '/settings/logs': typeof AuthenticatedSettingsLogsRoute
  '/settings/menus': typeof AuthenticatedSettingsMenusRoute
  '/settings/permissions': typeof AuthenticatedSettingsPermissionsRoute
  '/settings/roles': typeof AuthenticatedSettingsRolesRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/org/notices/$noticeId': typeof AuthenticatedOrgNoticesNoticeIdRoute
}
export interface FileRoutesByTo {
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/500': typeof R500Route
  '/sign-in': typeof authSignInRoute
  '/account': typeof AuthenticatedAccountRoute
  '/my-notices': typeof AuthenticatedMyNoticesRoute
  '/': typeof AuthenticatedIndexRoute
  '/org/chart': typeof AuthenticatedOrgChartRoute
  '/org/depts': typeof AuthenticatedOrgDeptsRoute
  '/org/directory': typeof AuthenticatedOrgDirectoryRoute
  '/org/notices': typeof AuthenticatedOrgNoticesRoute
  '/org/posts': typeof AuthenticatedOrgPostsRoute
  '/settings/dicts': typeof AuthenticatedSettingsDictsRoute
  '/settings/logs': typeof AuthenticatedSettingsLogsRoute
  '/settings/menus': typeof AuthenticatedSettingsMenusRoute
  '/settings/permissions': typeof AuthenticatedSettingsPermissionsRoute
  '/settings/roles': typeof AuthenticatedSettingsRolesRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/org/notices/$noticeId': typeof AuthenticatedOrgNoticesNoticeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/500': typeof R500Route
  '/(auth)/sign-in': typeof authSignInRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/my-notices': typeof AuthenticatedMyNoticesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/org/chart': typeof AuthenticatedOrgChartRoute
  '/_authenticated/org/depts': typeof AuthenticatedOrgDeptsRoute
  '/_authenticated/org/directory': typeof AuthenticatedOrgDirectoryRoute
  '/_authenticated/org/notices': typeof AuthenticatedOrgNoticesRoute
  '/_authenticated/org/posts': typeof AuthenticatedOrgPostsRoute
  '/_authenticated/settings/dicts': typeof AuthenticatedSettingsDictsRoute
  '/_authenticated/settings/logs': typeof AuthenticatedSettingsLogsRoute
  '/_authenticated/settings/menus': typeof AuthenticatedSettingsMenusRoute
  '/_authenticated/settings/permissions': typeof AuthenticatedSettingsPermissionsRoute
  '/_authenticated/settings/roles': typeof AuthenticatedSettingsRolesRoute
  '/_authenticated/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/org/notices_/$noticeId': typeof AuthenticatedOrgNoticesNoticeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/403'
    | '/404'
    | '/500'
    | '/sign-in'
    | '/account'
    | '/my-notices'
    | '/org/chart'
    | '/org/depts'
    | '/org/directory'
    | '/org/notices'
    | '/org/posts'
    | '/settings/dicts'
    | '/settings/logs'
    | '/settings/menus'
    | '/settings/permissions'
    | '/settings/roles'
    | '/settings/users'
    | '/settings/'
    | '/org/notices/$noticeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/403'
    | '/404'
    | '/500'
    | '/sign-in'
    | '/account'
    | '/my-notices'
    | '/'
    | '/org/chart'
    | '/org/depts'
    | '/org/directory'
    | '/org/notices'
    | '/org/posts'
    | '/settings/dicts'
    | '/settings/logs'
    | '/settings/menus'
    | '/settings/permissions'
    | '/settings/roles'
    | '/settings/users'
    | '/settings'
    | '/org/notices/$noticeId'
  id:
    | '__root__'
    | '/(auth)'
    | '/_authenticated'
    | '/403'
    | '/404'
    | '/500'
    | '/(auth)/sign-in'
    | '/_authenticated/account'
    | '/_authenticated/my-notices'
    | '/_authenticated/'
    | '/_authenticated/org/chart'
    | '/_authenticated/org/depts'
    | '/_authenticated/org/directory'
    | '/_authenticated/org/notices'
    | '/_authenticated/org/posts'
    | '/_authenticated/settings/dicts'
    | '/_authenticated/settings/logs'
    | '/_authenticated/settings/menus'
    | '/_authenticated/settings/permissions'
    | '/_authenticated/settings/roles'
    | '/_authenticated/settings/users'
    | '/_authenticated/settings/'
    | '/_authenticated/org/notices_/$noticeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  R403Route: typeof R403Route
  R404Route: typeof R404Route
  R500Route: typeof R500Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/500': {
      id: '/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof R500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-notices': {
      id: '/_authenticated/my-notices'
      path: '/my-notices'
      fullPath: '/my-notices'
      preLoaderRoute: typeof AuthenticatedMyNoticesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/users': {
      id: '/_authenticated/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthenticatedSettingsUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/roles': {
      id: '/_authenticated/settings/roles'
      path: '/settings/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof AuthenticatedSettingsRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/permissions': {
      id: '/_authenticated/settings/permissions'
      path: '/settings/permissions'
      fullPath: '/settings/permissions'
      preLoaderRoute: typeof AuthenticatedSettingsPermissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/menus': {
      id: '/_authenticated/settings/menus'
      path: '/settings/menus'
      fullPath: '/settings/menus'
      preLoaderRoute: typeof AuthenticatedSettingsMenusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/logs': {
      id: '/_authenticated/settings/logs'
      path: '/settings/logs'
      fullPath: '/settings/logs'
      preLoaderRoute: typeof AuthenticatedSettingsLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/dicts': {
      id: '/_authenticated/settings/dicts'
      path: '/settings/dicts'
      fullPath: '/settings/dicts'
      preLoaderRoute: typeof AuthenticatedSettingsDictsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/org/posts': {
      id: '/_authenticated/org/posts'
      path: '/org/posts'
      fullPath: '/org/posts'
      preLoaderRoute: typeof AuthenticatedOrgPostsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/org/notices': {
      id: '/_authenticated/org/notices'
      path: '/org/notices'
      fullPath: '/org/notices'
      preLoaderRoute: typeof AuthenticatedOrgNoticesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/org/directory': {
      id: '/_authenticated/org/directory'
      path: '/org/directory'
      fullPath: '/org/directory'
      preLoaderRoute: typeof AuthenticatedOrgDirectoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/org/depts': {
      id: '/_authenticated/org/depts'
      path: '/org/depts'
      fullPath: '/org/depts'
      preLoaderRoute: typeof AuthenticatedOrgDeptsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/org/chart': {
      id: '/_authenticated/org/chart'
      path: '/org/chart'
      fullPath: '/org/chart'
      preLoaderRoute: typeof AuthenticatedOrgChartRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/org/notices_/$noticeId': {
      id: '/_authenticated/org/notices_/$noticeId'
      path: '/org/notices/$noticeId'
      fullPath: '/org/notices/$noticeId'
      preLoaderRoute: typeof AuthenticatedOrgNoticesNoticeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authSignInRoute: typeof authSignInRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authSignInRoute: authSignInRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedMyNoticesRoute: typeof AuthenticatedMyNoticesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedOrgChartRoute: typeof AuthenticatedOrgChartRoute
  AuthenticatedOrgDeptsRoute: typeof AuthenticatedOrgDeptsRoute
  AuthenticatedOrgDirectoryRoute: typeof AuthenticatedOrgDirectoryRoute
  AuthenticatedOrgNoticesRoute: typeof AuthenticatedOrgNoticesRoute
  AuthenticatedOrgPostsRoute: typeof AuthenticatedOrgPostsRoute
  AuthenticatedSettingsDictsRoute: typeof AuthenticatedSettingsDictsRoute
  AuthenticatedSettingsLogsRoute: typeof AuthenticatedSettingsLogsRoute
  AuthenticatedSettingsMenusRoute: typeof AuthenticatedSettingsMenusRoute
  AuthenticatedSettingsPermissionsRoute: typeof AuthenticatedSettingsPermissionsRoute
  AuthenticatedSettingsRolesRoute: typeof AuthenticatedSettingsRolesRoute
  AuthenticatedSettingsUsersRoute: typeof AuthenticatedSettingsUsersRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedOrgNoticesNoticeIdRoute: typeof AuthenticatedOrgNoticesNoticeIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedMyNoticesRoute: AuthenticatedMyNoticesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedOrgChartRoute: AuthenticatedOrgChartRoute,
  AuthenticatedOrgDeptsRoute: AuthenticatedOrgDeptsRoute,
  AuthenticatedOrgDirectoryRoute: AuthenticatedOrgDirectoryRoute,
  AuthenticatedOrgNoticesRoute: AuthenticatedOrgNoticesRoute,
  AuthenticatedOrgPostsRoute: AuthenticatedOrgPostsRoute,
  AuthenticatedSettingsDictsRoute: AuthenticatedSettingsDictsRoute,
  AuthenticatedSettingsLogsRoute: AuthenticatedSettingsLogsRoute,
  AuthenticatedSettingsMenusRoute: AuthenticatedSettingsMenusRoute,
  AuthenticatedSettingsPermissionsRoute: AuthenticatedSettingsPermissionsRoute,
  AuthenticatedSettingsRolesRoute: AuthenticatedSettingsRolesRoute,
  AuthenticatedSettingsUsersRoute: AuthenticatedSettingsUsersRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedOrgNoticesNoticeIdRoute: AuthenticatedOrgNoticesNoticeIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  R403Route: R403Route,
  R404Route: R404Route,
  R500Route: R500Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
