/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/(auth)/sign-in': RouteRecordInfo<
      '/(auth)/sign-in',
      '/sign-in',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(authenticated)/': RouteRecordInfo<
      '/(authenticated)/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(authenticated)/account': RouteRecordInfo<
      '/(authenticated)/account',
      '/account',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(authenticated)/my-notices': RouteRecordInfo<
      '/(authenticated)/my-notices',
      '/my-notices',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(authenticated)/org/chart': RouteRecordInfo<
      '/(authenticated)/org/chart',
      '/org/chart',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(authenticated)/org/depts': RouteRecordInfo<
      '/(authenticated)/org/depts',
      '/org/depts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(authenticated)/org/directory': RouteRecordInfo<
      '/(authenticated)/org/directory',
      '/org/directory',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(authenticated)/org/notices': RouteRecordInfo<
      '/(authenticated)/org/notices',
      '/org/notices',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(authenticated)/org/notices.[noticeId]': RouteRecordInfo<
      '/(authenticated)/org/notices.[noticeId]',
      '/org/notices/:noticeId',
      { noticeId: ParamValue<true> },
      { noticeId: ParamValue<false> },
      | never
    >,
    '/(authenticated)/org/posts': RouteRecordInfo<
      '/(authenticated)/org/posts',
      '/org/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(authenticated)/settings/': RouteRecordInfo<
      '/(authenticated)/settings/',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(authenticated)/settings/dicts': RouteRecordInfo<
      '/(authenticated)/settings/dicts',
      '/settings/dicts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(authenticated)/settings/logs': RouteRecordInfo<
      '/(authenticated)/settings/logs',
      '/settings/logs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(authenticated)/settings/menus': RouteRecordInfo<
      '/(authenticated)/settings/menus',
      '/settings/menus',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(authenticated)/settings/permissions': RouteRecordInfo<
      '/(authenticated)/settings/permissions',
      '/settings/permissions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(authenticated)/settings/roles': RouteRecordInfo<
      '/(authenticated)/settings/roles',
      '/settings/roles',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(authenticated)/settings/users': RouteRecordInfo<
      '/(authenticated)/settings/users',
      '/settings/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(errors)/403': RouteRecordInfo<
      '/(errors)/403',
      '/403',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(errors)/404': RouteRecordInfo<
      '/(errors)/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(errors)/500': RouteRecordInfo<
      '/(errors)/500',
      '/500',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/(auth)/sign-in.vue': {
      routes:
        | '/(auth)/sign-in'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(authenticated)/index.vue': {
      routes:
        | '/(authenticated)/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(authenticated)/account.vue': {
      routes:
        | '/(authenticated)/account'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(authenticated)/my-notices.vue': {
      routes:
        | '/(authenticated)/my-notices'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(authenticated)/org/chart.vue': {
      routes:
        | '/(authenticated)/org/chart'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(authenticated)/org/depts.vue': {
      routes:
        | '/(authenticated)/org/depts'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(authenticated)/org/directory.vue': {
      routes:
        | '/(authenticated)/org/directory'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(authenticated)/org/notices.vue': {
      routes:
        | '/(authenticated)/org/notices'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(authenticated)/org/notices.[noticeId].vue': {
      routes:
        | '/(authenticated)/org/notices.[noticeId]'
      views:
        | never
      pathParamNames:
        | 'noticeId'
    }
    'src/pages/(authenticated)/org/posts.vue': {
      routes:
        | '/(authenticated)/org/posts'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(authenticated)/settings/index.vue': {
      routes:
        | '/(authenticated)/settings/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(authenticated)/settings/dicts.vue': {
      routes:
        | '/(authenticated)/settings/dicts'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(authenticated)/settings/logs.vue': {
      routes:
        | '/(authenticated)/settings/logs'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(authenticated)/settings/menus.vue': {
      routes:
        | '/(authenticated)/settings/menus'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(authenticated)/settings/permissions.vue': {
      routes:
        | '/(authenticated)/settings/permissions'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(authenticated)/settings/roles.vue': {
      routes:
        | '/(authenticated)/settings/roles'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(authenticated)/settings/users.vue': {
      routes:
        | '/(authenticated)/settings/users'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(errors)/403.vue': {
      routes:
        | '/(errors)/403'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(errors)/404.vue': {
      routes:
        | '/(errors)/404'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(errors)/500.vue': {
      routes:
        | '/(errors)/500'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
      pathParamNames:
        | 'all'
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
